package worker

import java.util.UUID
import scala.concurrent.forkjoin.ThreadLocalRandom
import scala.concurrent.duration._
import akka.actor.Actor
import akka.actor.ActorLogging
import akka.actor.ActorRef

object WorkProducer {
  case object Tick
}

class WorkProducer(frontend: ActorRef) extends Actor with ActorLogging {
  import WorkProducer._
  import context.dispatcher
  def scheduler = context.system.scheduler
  def rnd = ThreadLocalRandom.current
  var n = 0
  
  def nextWorkId(): String =  {n = n + 1; n.toString}//UUID.randomUUID().toString



  override def preStart(): Unit =
    scheduler.scheduleOnce(5.seconds, self, Tick)

  // override postRestart so we don't call preStart and schedule a new Tick
  override def postRestart(reason: Throwable): Unit = ()

  val links = List(
    /*"http://feeds.bbci.co.uk/news/rss.xml",
    "http://feeds.bbci.co.uk/news/world/rss.xml",
    "http://feeds.bbci.co.uk/news/uk/rss.xml",
    "http://feeds.bbci.co.uk/news/business/rss.xml",
    "http://feeds.bbci.co.uk/news/politics/rss.xml",
    "http://feeds.bbci.co.uk/news/health/rss.xml",
    "http://feeds.bbci.co.uk/news/education/rss.xml",
    "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
    "http://feeds.bbci.co.uk/news/technology/rss.xml",
    "http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
    "http://rss.cnn.com/rss/edition.rss  ",
    "http://rss.cnn.com/rss/edition_world.rss",
    "http://rss.cnn.com/rss/edition_technology.rss",
    "http://www.livemint.com/rss/homepage",
    "http://www.livemint.com/rss/companies",
    "http://www.livemint.com/rss/consumer",
    "http://www.livemint.com/rss/opinion",
    "http://www.livemint.com/rss/money",
    "http://www.livemint.com/rss/industry",
    "http://www.livemint.com/rss/economy_politics",
    "http://www.thehindu.com/news/cities/bangalore/?service=rss",
    "http://www.thehindu.com/news/cities/chennai/?service=rss",
    "http://www.thehindu.com/news/cities/Coimbatore/?service=rss",
    "http://www.thehindu.com/news/cities/Delhi/?service=rss",
    "http://www.thehindu.com/news/cities/Hyderabad/?service=rss",
    "http://www.thehindu.com/news/cities/kozhikode/?service=rss",
    "http://www.thehindu.com/news/cities/mumbai/?service=rss",
    "http://www.thehindu.com/news/national/karnataka/?service=rss",
    "http://www.thehindu.com/news/national/andhra-pradesh/?service=rss",
    "http://www.thehindu.com/news/national/tamil-nadu/?service=rss",
    "http://www.thehindu.com/business/Economy/?service=rss",
    "http://www.thehindu.com/business/markets/?service=rss",
    "http://economictimes.indiatimes.com/News/rssfeeds/1715249553.cms",
    "http://economictimes.indiatimes.com/Markets/markets/rssfeeds/1977021501.cms",
    "http://economictimes.indiatimes.com/rssfeeds/837555174.cms",
    "http://economictimes.indiatimes.com/rssfeeds/2146842.cms",
    "http://economictimes.indiatimes.com/Personal-Finance/Mutual-Funds/rssfeeds/359241701.cms",
    "http://economictimes.indiatimes.com/Personal-Finance/Fixed-Deposits/rssfeeds/2146932.cms",
    "http://economictimes.indiatimes.com/Personal-Finance/Insurance/rssfeeds/1137301345.cms",
    * 
    */
    "http://indianexpress.com/section/sports/feed",
    "http://indianexpress.com/section/world/feed",
    "http://indianexpress.com/section/india/feed",
    "http://indianexpress.com/print/front-page/feed",
    "http://indianexpress.com/section/lifestyle/feed",
    "http://indianexpress.com/section/world/asia/feed",
    "http://indianexpress.com/section/opinion/editorials/feed",
    "http://indianexpress.com/section/sports/cricket/feed",
    "http://www.indianexpress.com/section/lifestyle/health/feed",
    "http://indianexpress.com/section/india/crime/feed",
    "http://indianexpress.com/section/opinion/feed",
    "http://www.indianexpress.com/section/cities/delhi/feed",
    "http://www.indianexpress.com/section/cities/lucknow/feed",
    "http://www.indianexpress.com/section/cities/pune/feed",
    "http://indianexpress.com/section/cities/chandigarh/feed",
    "http://www.indianexpress.com/section/cities/mumbai/feed",
    "http://www.indianexpress.com/section/cities/kolkata/feed",
    "http://indianexpress.com/section/cities/ludhiana/feed",
    "http://indianexpress.com/section/lifestyle/life-style",
    "http://www.indianexpress.com/section/world/europe/feed",
    "http://www.indianexpress.com/sports/football/feed",
    "http://indianexpress.com/section/india/education/feed",
    "http://indianexpress.com/section/india/education/feed",
    "http://indianexpress.com/section/lifestyle/food/feed",
    "http://indianexpress.com/print/national-network/feed",
    "http://indianexpress.com/section/sports/tennis/feed",
    "http://indianexpress.com/section/india/maharashtra/feed",
    "http://indianexpress.com/section/lifestyle/fashion/feed",
    "http://indianexpress.com/section/entertainment/feed",
    "http://indianexpress.com/section/world/indians-abroad/feed",
    "http://indianexpress.com/section/india/uttar-pradesh/feed",
    "http://indianexpress.com/section/technology/feed",
    "http://indianexpress.com/print/eye/feed",
    "http://indianexpress.com/section/sports/motor-sport/feed",
    "http://indianexpress.com/section/world/asia/feed",
    "http://indianexpress.com/section/india/politics/feed",
    "http://indianexpress.com/section/sports/golf/feed",
    "http://indianexpress.com/section/india/regional-india/feed",
    "http://indianexpress.com/section/world/climate-change/feed",
    "http://indianexpress.com/section/sports/hockey/feed",
    "http://indianexpress.com/section/sports/feed",
    "http://indianexpress.com/section/sports/sport-others/feed",
    "http://indianexpress.com/section/india/west-bengal/feed",
    "http://indianexpress.com/section/india/punjab-and-haryana/feed",
    "http://indianexpress.com/section/opinion/letters-to-editor/feed",
    "http://indianexpress.com/print/rxpress/feed",
    "http://indianexpress.com/print/most-powerful-indians/feed",
    "http://indianexpress.com/print/from-the-fields/feed",
    "http://indianexpress.com/print/delhi-confidential/feed",
    "http://indianexpress.com/section/entertainment/movie-review/feed",
    "http://indianexpress.com/section/opinion/columns/feed",
    "http://indianexpress.com/print/reviews-books/feed",
    "http://indianexpress.com/print/reviews-dvd/feed",
    "http://indianexpress.com/print/reviews-music/feed",
    "http://indianexpress.com/print/estates/feed",
    "http://indianexpress.com/section/entertainment/regional/feed",
    "http://indianexpress.com/section/entertainment/hollywood/feed",
    "http://indianexpress.com/section/entertainment/bollywood/feed",
    "http://indianexpress.com/print/express-adda/feed",
    "http://indianexpress.com/topic/the-idea-exchange/feed",
    "http://indianexpress.com/picture-gallery-section/entertainment-gallery/feed",
    "http://indianexpress.com/picture-gallery-section/sports-gallery/feed",
    "http://indianexpress.com/picture-gallery-section/picture-gallery-others/feed",
    "http://indianexpress.com/picture-gallery-section/lifestyle-gallery/feed",
    "http://indianexpress.com/picture-gallery-section/photo-archives/feed",
    "http://www.newindianexpress.com/top_news/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/nation/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.newindianexpress.com/world/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.newindianexpress.com/magazine/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.newindianexpress.com/columns/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.newindianexpress.com/prabhu_chawla/columns/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.newindianexpress.com/editorials/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.newindianexpress.com/auto/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.newindianexpress.com/thesundaystandard/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.newindianexpress.com/business/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/entertainment/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/sport/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/cricket/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/cricket/ipl/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/states/andhra_pradesh/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/states/karnataka/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/states/kerala/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/states/tamil_nadu/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/states/telangana/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/states/odisha/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/cities/bengaluru/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/cities/chennai/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/cities/kochi/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/cities/thiruvananthapuram/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/cities/hyderabad/?widgetName=rssfeed&widgetId=534391&getXmlFeed=true",
    "http://www.newindianexpress.com/lifestyle/travel/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.newindianexpress.com/lifestyle/food/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.newindianexpress.com/lifestyle/health/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.newindianexpress.com/lifestyle/books/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.newindianexpress.com/lifestyle/spirituality/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.newindianexpress.com/lifestyle/tech/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.newindianexpress.com/education/edex/?widgetName=rssfeed&widgetId=276210&getXmlFeed=true",
    "http://www.deccanherald.com/rss-internal/top-stories.rss",
    "http://www.deccanherald.com/rss-internal/breaking-news.rss",
    "http://www.deccanherald.com/rss/election-news.rss",
    "http://www.deccanherald.com/rss/election-blogs.rss",
    "http://www.deccanherald.com/rss/news.rss",
    "http://www.deccanherald.com/rss/city.rss",
    "http://www.deccanherald.com/rss/district.rss",
    "http://www.deccanherald.com/rss/state.rss",
    "http://www.deccanherald.com/rss/national.rss",
    "http://www.deccanherald.com/rss/international.rss",
    "http://www.deccanherald.com/rss/business.rss",
    "http://www.deccanherald.com/rss/environment.rss",
    "http://www.deccanherald.com/rss/entertainment.rss",
    "http://www.deccanherald.com/rss/sports.rss",
    "http://www.deccanherald.com/rss/delhi.rss",
    "http://www.deccanherald.com/rss/metrolife.rss",
    "http://www.deccanherald.com/rss/metro.rss",
    "http://www.deccanherald.com/rss/region.rss",
    "http://www.deccanherald.com/rss/supplements.rss",
    "http://www.deccanherald.com/rss/sunday.rss",
    "http://www.deccanherald.com/rss/sportscene.rss",
    "http://www.deccanherald.com/rss/sunday-sunday-herald.rss",
    "http://www.deccanherald.com/rss/monday.rss",
    "http://www.deccanherald.com/rss/economy-business.rss",
    "http://www.deccanherald.com/rss/art-review.rss",
    "http://www.deccanherald.com/rss/monday-metrolife.rss",
    "http://www.deccanherald.com/rss/tuesday.rss",
    "http://www.deccanherald.com/rss/spectrum.rss",
    "http://www.deccanherald.com/rss/science-technology.rss",
    "http://www.deccanherald.com/rss/environment.rss",
    "http://www.deccanherald.com/rss/tuesday-metrolife.rss",
    "http://www.deccanherald.com/rss/wednesday.rss",
    "http://www.deccanherald.com/rss/dh-avenues.rss",
    "http://www.deccanherald.com/rss/cyber-space.rss",
    "http://www.deccanherald.com/rss/wednesday-metrolife.rss",
    "http://www.deccanherald.com/rss/thursday.rss",
    "http://www.deccanherald.com/rss/dh-education.rss",
    "http://www.deccanherald.com/rss/thursday-metrolife.rss",
    "http://www.deccanherald.com/rss/friday.rss",
    "http://www.deccanherald.com/rss/open-sesame.rss",
    "http://www.deccanherald.com/rss/homes-interiors.rss",
    "http://www.deccanherald.com/rss/friday-metrolife.rss",
    "http://www.deccanherald.com/rss/saturday.rss",
    "http://www.deccanherald.com/rss/deepavali-special.rss",
    "http://www.deccanherald.com/rss/movie-reviews.rss",
    "http://www.deccanherald.com/rss/she.rss",
    "http://www.deccanherald.com/rss/living.rss",
    "http://www.deccanherald.com/rss/saturday-metrolife.rss",
    "http://www.deccanherald.com/rss/opinion.rss",
    "http://www.deccanherald.com/rss/in-perspective.rss",
    "http://www.deccanherald.com/rss/net-mail.rss",
    "http://www.deccanherald.com/rss/right-middle.rss",
    "http://www.deccanherald.com/rss/columns.rss",
    "http://www.deccanherald.com/rss/khushwant-singh.rss",
    "http://www.deccanherald.com/rss/kuldip-nayar.rss",
    "http://www.deccanherald.com/rss/m-j-akbar.rss",
    "http://www.deccanherald.com/rss/oasis.rss",
    "http://www.deccanherald.com/rss/rajdeep-sardesai.rss",
    "http://www.deccanherald.com/rss/analysis.rss",
    "http://www.deccanherald.com/rss/panorama.rss",
    "http://www.business-standard.com/rss/home_page_top_stories.rss",
    "http://www.business-standard.com/rss/latest.rss",
    "http://www.business-standard.com/rss/general-news.rss",
    "http://www.business-standard.com/rss/todays-paper.rss",
    "http://www.business-standard.com/rss/market.rss",
    "http://www.business-standard.com/rss/most-viewed.rss",
    "http://www.business-standard.com/rss/companies-101.rss",
    "http://www.business-standard.com/rss/companies-news-10101.rss",
    "http://www.business-standard.com/rss/companies-results-10103.rss",
    "http://www.business-standard.com/rss/companies-people-in-news-10109.rss",
    "http://www.business-standard.com/rss/companies-bs-1000-10114.rss",
    "http://www.business-standard.com/rss/companies-features-10102.rss",
    "http://www.business-standard.com/rss/companies-opinion-10104.rss",
    "http://www.business-standard.com/rss/companies-start-ups-10113.rss",
    "http://www.business-standard.com/rss/companies-specials-10115.rss",
    "http://www.business-standard.com/rss/economy-policy-102.rss",
    "http://www.business-standard.com/rss/economy-policy-news-10201.rss",
    "http://www.business-standard.com/rss/economy-policy-opinion-10204.rss",
    "http://www.business-standard.com/rss/economy-policy-specials-10211.rss",
    "http://www.business-standard.com/rss/economy-policy-features-10202.rss",
    "http://www.business-standard.com/rss/economy-policy-people-in-news-10210.rss",
    "http://www.business-standard.com/rss/finance-103.rss",
    "http://www.business-standard.com/rss/finance-news-10301.rss",
    "http://www.business-standard.com/rss/finance-columnists-10307.rss",
    "http://www.business-standard.com/rss/finance-people-in-news-10310.rss",
    "http://www.business-standard.com/rss/finance-features-10302.rss",
    "http://www.business-standard.com/rss/finance-editorials-10308.rss",
    "http://www.business-standard.com/rss/beyond-business-104.rss",
    "http://www.business-standard.com/rss/beyond-business-news-10401.rss",
    "http://www.business-standard.com/rss/beyond-business-people-10403.rss",
    "http://www.business-standard.com/rss/beyond-business-columns-10408.rss",
    "http://www.business-standard.com/rss/beyond-business-features-10402.rss",
    "http://www.business-standard.com/rss/beyond-business-books-10405.rss",
    "http://www.business-standard.com/rss/beyond-business-motoring-10410.rss",
    "http://www.business-standard.com/rss/opinion-105.rss",
    "http://www.business-standard.com/rss/opinion-editorial-10501.rss",
    "http://www.business-standard.com/rss/opinion-financial-x-ray-10503.rss",
    "http://www.business-standard.com/rss/opinion-chinese-10506.rss",
    "http://www.business-standard.com/rss/opinion-business-law-taxation-10512.rss",
    "http://www.business-standard.com/rss/opinion-special-10516.rss",
    "http://www.business-standard.com/rss/opinion-columns-10502.rss",
    "http://www.business-standard.com/rss/opinion-people-10504.rss",
    "http://www.business-standard.com/rss/opinion-lunch-10507.rss",
    "http://www.business-standard.com/rss/opinion-blogs-10514.rss",
    "http://www.business-standard.com/rss/markets-106.rss",
    "http://www.business-standard.com/rss/markets-news-10601.rss",
    "http://www.business-standard.com/rss/markets-features-10610.rss",
    "http://www.business-standard.com/rss/markets-opinion-10613.rss",
    "http://www.business-standard.com/rss/markets-stocks-10618.rss",
    "http://www.business-standard.com/rss/markets-commodities-10608.rss",
    "http://www.business-standard.com/rss/markets-ipos-10611.rss",
    "http://www.business-standard.com/rss/markets-people-in-news-10615.rss",
    "http://www.business-standard.com/rss/markets-bs-fund-manager-10620.rss",
    "http://www.business-standard.com/rss/management-107.rss",
    "http://www.business-standard.com/rss/management-news-10701.rss",
    "http://www.business-standard.com/rss/management-books-ideas-10704.rss",
    "http://www.business-standard.com/rss/management-people-10706.rss",
    "http://www.business-standard.com/rss/management-features-10702.rss",
    "http://www.business-standard.com/rss/management-columns-10705.rss",
    "http://www.business-standard.com/rss/technology-108.rss").toIterator

  def receive = {
    case Tick =>
      if (links.hasNext) {
        val link = links.next()
        log.info("Produced work: {}", link)
        val work = Work(nextWorkId(), link)
        frontend ! work
        context.become(waitAccepted(work), discardOld = false)
      }
  }

  def waitAccepted(work: Work): Actor.Receive = {
    case Frontend.Ok =>
      context.unbecome()
      //scheduler.scheduleOnce(rnd.nextInt(3, 10).seconds, self, Tick)
      self ! Tick
    case Frontend.NotOk =>
      log.info("Work not accepted, retry after a while")
      scheduler.scheduleOnce(3.seconds, frontend, work)
  }

}